### PR TITLE
feat: create mint page

### PR DESCRIPTION
**Pull request by berteotti**
Create mint page without contract logic. Mint NFT section has different spacing from figma.

Screenshot 2023-08-30 at 14 45 37

### CODE REVIEW

**Comment by Diogomartf** [comment]
NFT image is too big, should have a max width about 420px, something like: `max-w-md` or `max-w-sm`.

image

**Comment by Diogomartf** [comment]
Mobile view is not ideal, would be better to have the mint button at the bottom, but that would requires us to use a grid and might be a lot more work for the usage.

image

**Review by Diogomartf — APPROVED** [review]

**Comment by berteotti** [comment]
> Mobile view is not ideal, would be better to have the mint button at the bottom, but that would requires us to use a grid and might be a lot more work for the usage.
> 
> image

We can put the button on the bottom. But what about UX? Scrolling to mint doesn't seem a good experience to me. I just want to mint so I can Stack.

**Comment by berteotti** [comment]
Should we change the text to `Mint (FREE)` ?

**Comment by Diogomartf** [comment]
> > Mobile view is not ideal, would be better to have the mint button at the bottom, but that would requires us to use a grid and might be a lot more work for the usage.
> > image
> 
> We can put the button on the bottom. But what about UX? Scrolling to mint doesn't seem a good experience to me. I just want to mint so I can Stack.

okay, I'll buy that.

**Pull request merged**
